### ISSUE TITLE
Possible Bug In Decrypt

### ISSUE THREAD

**Issue by brosert** [ytti/router_crypt#2]
New to github and not sure how to update this myself (or whether I even can).
IF the Junos encryption starts with a particular character (that maps to 0 in EXTRA) we hit an exception in nibble about bad length and invalidPW.

Basically this is because len passed in the first time is 0, so the nib becomes the entire string (which mismatches len, obviously)

**Comment by ninjaltd** [comment]
Ran into the same issue today.  I just created a pull request with a fix.

**Comment by ytti** [comment]
Is it this issue: https://github.com/ytti/router_crypt/pull/3

**Comment by qnet-herwin** [comment]
Could this be released as version 0.4.1?

**Comment by ytti** [comment]
Yes, if you don't have it in a week, please notify me. I'm traveling this week and I'm not sure if I'll have time earlier than next Monday.

**Comment by qnet-herwin** [comment]
Gentle reminder ;)

**Comment by ytti** [comment]
I just uploaded 0.4.1 to rubygems
